export const knownAbbreviations = {
  'university of lagos': 'UNILAG', 'unilag': 'UNILAG',
  'obafemi awolowo university': 'OAU', 'oau ile-ife': 'OAU',
  'ahmadu bello university': 'ABU', 'abu zaria': 'ABU',
  'university of nigeria nsukka': 'UNN',
  'university of nigeria': 'UNN',
  'covenant university': 'CU',
  'university of ibadan': 'UI',
  'lagos state university': 'LASU',
  'university of benin': 'UNIBEN',
  'university of port harcourt': 'UNIPORT',
  'university of ilorin': 'UNILORIN',
  'babcock university': 'BU',
  'nnamdi azikiwe university': 'UNIZIK',
  'rivers state university': 'RSU',
  'enugu state university of technology (esut)': 'ESUT',
  'enugu state university of technology': 'ESUT',
  'esut': 'ESUT',
  'university of ghana': 'UG',
  'kwame nkrumah university of science and technology': 'KNUST',
  'university of nairobi': 'UON',
  'kenyatta university': 'KU',
  'makerere university': 'MAK',
  'university of cape town': 'UCT',
  'university of the witwatersrand': 'WITS',
  'stellenbosch university': 'SU',
  'university of pretoria': 'UP',
  'addis ababa university': 'AAU',
  'federal university of technology akure': 'FUTA',
  'federal university of technology owerri': 'FUTO',
  'federal university of technology minna': 'FUTMINNA',
  'federal university of agriculture abeokuta': 'FUNAAB',
  'federal university oye-ekiti': 'FUOYE',
  'federal university ndufu alike ikwo': 'FUNAI',
  'federal university dutse': 'FUD',
  'federal university dutsin-ma': 'FUDMA',
  'federal university lokoja': 'FUL',
  'federal university kashere': 'FUK',
  'federal university gusau': 'FUGUS',
  'federal university birnin kebbi': 'FUBK',
  'federal university wukari': 'FUW',
  'federal university lafia': 'FULAFIA',
  'federal university gashua': 'FUGASHUA',
  'bayero university kano': 'BUK',
  'university of calabar': 'UNICAL',
  'university of jos': 'UNIJOS',
  'university of uyo': 'UNIUYO',
  'university of maiduguri': 'UNIMAID',
  'university of abuja': 'UNIABUJA',
  'ekiti state university': 'EKSU',
  'olabisi onabanjo university': 'OOU',
  'adekunle ajasin university': 'AAUA',
  'ambrose alli university': 'AAU',
  'delta state university': 'DELSU',
  'niger delta university': 'NDU',
  'imo state university': 'IMSU',
  'abia state university': 'ABSU',
  'anambra state university': 'ANSU',
  'benue state university': 'BSU',
  'kogi state university': 'KSU',
  'kaduna state university': 'KASU',
  'nasarawa state university': 'NSUK',
  'gombe state university': 'GSU',
  'adamawa state university': 'ADSU',
  'taraba state university': 'TSU',
  'plateau state university': 'PLASU',
  'yobe state university': 'YSU',
  'sokoto state university': 'SSU',
  'kebbi state university': 'KSUSTA',
  'zamfara state university': 'ZSU',
  'osun state university': 'UNIOSUN',
  'ondo state university of science and technology': 'OSUSTECH',
  'kwara state university': 'KWASU',
  'ebonyi state university': 'EBSU',
  'national open university of nigeria': 'NOUN',
  'nigerian defence academy': 'NDA',
  'air force institute of technology': 'AFIT',
  'pan-atlantic university': 'PAU',
  'american university of nigeria': 'AUN',
  'baze university': 'BAZE',
  'lead city university': 'LCU',
  'benson idahosa university': 'BIU',
  'igbinedion university': 'IUO',
  'bowen university': 'BOWEN',
  'madonna university': 'MU',
  'caritas university': 'CARITAS',
  'joseph ayo babalola university': 'JABU',
  'adeleke university': 'AU',
  'afe babalola university': 'ABUAD',
  'elizade university': 'EU',
  'rhema university': 'RU',
  'tansian university': 'TU',
  'wellspring university': 'WU',
  'novena university': 'NU',
  'crawford university': 'CU',
  'landmark university': 'LMU',
  'mountain top university': 'MTU',
  'summit university': 'SU',
  'hallmark university': 'HU',
  'mchenry university': 'MHU',
  'augustine university': 'AUI',
  'university of ghana business school': 'UGBS',
  'university of cape coast': 'UCC',
  'university of education winneba': 'UEW',
  'university of ghana medical school': 'UGMS',
  'kwame nkrumah university': 'KNUST',
  'university for development studies': 'UDS',
  'university of mines and technology': 'UMAT',
  'university of energy and natural resources': 'UENR',
  'methodist university college ghana': 'MUCG',
  'central university college': 'CUC',
  'valley view university': 'VVU',
  'university of ghana distance education': 'UGDE',
  'university of professional studies': 'UPSA',
  'wisconsin international university college': 'WIUC',
  'zenith university college': 'ZC',
  'regional maritime university': 'RMU',
  'ghana institute of management and public administration': 'GIMPA',
  'uni of professional studies accra': 'UPSA',
}

export const schoolColors = {
  'university of lagos': '#003366', 'unilag': '#003366',
  'oau ile-ife': '#006400', 'obafemi awolowo university': '#006400',
  'abu zaria': '#8B0000', 'ahmadu bello university': '#8B0000',
  'covenant university': '#722F37',
  'university of ibadan': '#003399',
  'university of benin': '#006633',
  'lagos state university': '#CC0000',
  'university of ghana': '#006B3F',
  'university of nairobi': '#003366',
  'makerere university': '#006B3F',
  'university of cape town': '#003380',
  'university of the witwatersrand': '#003087',
  'enugu state university of technology (esut)': '#006400',
  'enugu state university of technology': '#006400',
  'esut': '#006400',
}

export function getSchoolAbbr(school) {
  if (!school) return '?'
  const lower = school.toLowerCase().trim()
  if (knownAbbreviations[lower]) return knownAbbreviations[lower]
  return school.split(' ').filter(w => w.length > 2).map(w => w[0].toUpperCase()).join('').slice(0, 6) || school.slice(0, 4).toUpperCase()
}

export function stringToColor(school) {
  if (!school) return '#008751'
  const lower = school.toLowerCase().trim()
  if (schoolColors[lower]) return schoolColors[lower]
  let hash = 0
  for (let i = 0; i < lower.length; i++) hash = lower.charCodeAt(i) + ((hash << 5) - hash)
  const palette = ['#008751', '#FF9F1C', '#1F2A1F', '#e63946', '#457b9d', '#6a4c93', '#f4a261', '#2a9d8f']
  return palette[Math.abs(hash) % palette.length]
}
